# Generated by Django 3.2.5 on 2021-07-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_site_dataManage_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=' اطلاعات مسئولین')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('v', 'نمایش'), ('n', 'عدم نمایش')], default=1, max_length=2, verbose_name='وضعیت')),
                ('managerAccept', models.CharField(choices=[('t', 'تایید'), ('nt', 'عدم تایید')], default=1, max_length=2, verbose_name='تایید مدیر')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Body_Manage', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'اطلاعات مسئولین',
                'verbose_name_plural': 'اطلاعات مسئولین',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Body_site_data_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='لینک ها')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس لینک')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('v', 'نمایش'), ('n', 'عدم نمایش')], max_length=2, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Body_Links', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک ها',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Body_site_data_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=' اطلاعات صندوق')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('v', 'نمایش'), ('n', 'عدم نمایش')], max_length=2, verbose_name='وضعیت')),
                ('managerAccept', models.CharField(choices=[('t', 'تایید'), ('nt', 'عدم تایید')], max_length=2, verbose_name='تایید مدیر')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Body_Data', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'اطلاعات صندوق',
                'verbose_name_plural': 'اطلاعات صندوق',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Body_site_data_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='آدرس')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('v', 'نمایش'), ('n', 'عدم نمایش')], max_length=2, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Body_Address', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Body_News_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس خبر')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویرخبر')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('v', 'نمایش'), ('n', 'عدم نمایش')], default='n', max_length=2, verbose_name='وضعیت')),
                ('managerAccept', models.CharField(choices=[('t', 'تایید'), ('nt', 'عدم تایید')], default='nt', max_length=2, verbose_name='تایید مدیر')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Body_News', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'خبر و اطلاعیه',
                'verbose_name_plural': 'خبرها و اطلاعیه ها',
                'ordering': ['-publish'],
            },
        ),
    ]
